# permissions for end users to edit resourcecreators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: assignment-3
    app.kubernetes.io/managed-by: kustomize
  name: resourcecreator-editor-role
rules:
- apiGroups:
  - creator.m3.io
  resources:
  - resourcecreators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - creator.m3.io
  resources:
  - resourcecreators/status
  verbs:
  - get
