---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - creator.m3.io
  resources:
  - resourcecreators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - creator.m3.io
  resources:
  - resourcecreators/finalizers
  verbs:
  - update
- apiGroups:
  - creator.m3.io
  resources:
  - resourcecreators/status
  verbs:
  - get
  - patch
  - update
